Revert "macos without deployment target, given new fortran loading"
No, we stiil have the same issue in the github runner:

delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 11.0:
682
  /private/var/folders/_l/91ns3hs96sd11p4_lzxh1l140000gn/T/tmpytka65se/wheel/pyoorb/.dylibs/libquadmath.0.dylib has a minimum target of 15.0
683
  /private/var/folders/_l/91ns3hs96sd11p4_lzxh1l140000gn/T/tmpytka65se/wheel/pyoorb/.dylibs/libgfortran.5.dylib has a minimum target of 15.0
684
  Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=15.0' to update minimum supported macOS for this wheel.

This reverts commit 7fcfbc12cff3745e463bc93b3362184a8ef62bd5.